Repository Shweta2024/JavaScript-Projects, pull requests merged in 2022-12, with the labels that each got.

#76 Email validation checker
  Email-Validation-Checker/500.css
  Email-Validation-Checker/README.MD
  Email-Validation-Checker/index.html
  Email-Validation-Checker/logic.js
  Email-Validation-Checker/style.css
Labels: merged

#59 Signup31
  Login Signup form/README.md
  Login Signup form/images/undraw_creative_team_r90h-removebg-preview.png
  Login Signup form/images/undraw_creative_team_r90h.png
  Login Signup form/images/undraw_different_love_a3rg-removebg-preview.png
  Login Signup form/images/undraw_different_love_a3rg.png
  Login Signup form/index.html
  Login Signup form/script.js
  Login Signup form/style.css
Labels: To Be Merged 😍

#89 Twitter tweet box
  Twitter Tweet Box✨/MyCSS.css
  Twitter Tweet Box✨/MyHtml.html
  Twitter Tweet Box✨/MyJS.js
  Twitter Tweet Box✨/Readme.md
Labels: To Be Merged 😍

#85 text to speech converter
  text-to-speech/README.md
  text-to-speech/img/g.png
  text-to-speech/img/pauseIcon.svg
  text-to-speech/img/resumeIcon.svg
  text-to-speech/img/speakIcon.svg
  text-to-speech/img/stopIcon.svg
  text-to-speech/index.html
  text-to-speech/index.js
  text-to-speech/style.css
Labels: To Be Merged 😍

#77 Bad button
  Bad-Button/index.html
  Bad-Button/style.css
Labels: To Be Merged 😍

#57 Replaced text with drop-down menu
  Weather-App/Readme.md
  Weather-App/index.html
Labels: To Be Merged 😍

#91 Pair Games
  Pair Games/README.md
  Pair Games/images/Screenshot (338).png
  Pair Games/images/Screenshot (339).png
  Pair Games/images/Screenshot (340).png
  Pair Games/images/anaconda.png
  Pair Games/images/bee.png
  Pair Games/images/chameleon.png
  Pair Games/images/cockatoo.png
  Pair Games/images/crocodile.png
  Pair Games/images/gorilla.png
  Pair Games/images/macaw.png
  Pair Games/images/monkey.png
  Pair Games/images/piranha.png
  Pair Games/images/sloth.png
  Pair Games/images/tiger.png
  Pair Games/images/toucan.png
  Pair Games/index.html
  Pair Games/script.js
  Pair Games/style.css
Labels: To Be Merged 😍

#86 Ludo Game added.
  Ludo Game/README.md
  Ludo Game/img/dice 1.svg
  Ludo Game/img/dice 2.svg
  Ludo Game/img/dice 3.svg
  Ludo Game/img/dice 4.svg
  Ludo Game/img/dice 5.svg
  Ludo Game/img/dice 6.svg
  Ludo Game/src/index.html
  Ludo Game/src/script.js
  Ludo Game/src/style.css
Labels: To Be Merged 😍

#97 Quiz app
  Quiz-App/1000.css
  Quiz-App/README.md
  Quiz-App/chemistry.jpg
  Quiz-App/computer.jpg
  Quiz-App/index.html
  Quiz-App/js/chemistry.js
  Quiz-App/js/computer.js
  Quiz-App/js/maths.js
  Quiz-App/js/physics.js
  Quiz-App/maths.jpg
  Quiz-App/physics.jpg
  Quiz-App/style.css
  Quiz-App/subjects/chemistry/700.css
  Quiz-App/subjects/chemistry/bg1.jpg
  Quiz-App/subjects/chemistry/chemistry.html
  Quiz-App/subjects/chemistry/style.css
  Quiz-App/subjects/computer/700.css
  Quiz-App/subjects/computer/bg.jpg
  Quiz-App/subjects/computer/computer.html
  Quiz-App/subjects/computer/style.css
  Quiz-App/subjects/maths/700.css
  Quiz-App/subjects/maths/bg.jpg
  Quiz-App/subjects/maths/maths.html
  Quiz-App/subjects/maths/style.css
  Quiz-App/subjects/physics/700.css
  Quiz-App/subjects/physics/bg.jpg
  Quiz-App/subjects/physics/physics.html
  Quiz-App/subjects/physics/style.css
Labels: To Be Merged 😍

#94 Hangman game
  Hangman/ReadMe.md
  Hangman/app.js
  Hangman/assets/hangman-icon.png
  Hangman/index.html
  Hangman/style.css
Labels: To Be Merged 😍

#106 Countdown Timer added
  Countdown-Timer/README.md
  Countdown-Timer/countdown_timer.html
  Countdown-Timer/script.js
  Countdown-Timer/style.css
Labels: To Be Merged 😍

#100 Update index.html
  Weather-App/index.html
Labels: To Be Merged 😍

#112 Theme clock
  Theme-Clock/README.md
  Theme-Clock/cl1.jpg
  Theme-Clock/cl2.jpg
  Theme-Clock/cl3.png
  Theme-Clock/index.html
  Theme-Clock/logic.js
  Theme-Clock/style.css
Labels: To Be Merged 😍

#119 Responsive calculator at all screen sizes
  Calculator/README.md
  Calculator/indexx.html
  Calculator/style.css
Labels: To Be Merged 😍

#107 sliding cards project added
  sliding cards/Readme.md
  sliding cards/index.html
  sliding cards/script.js
  sliding cards/style.css
Labels: To Be Merged 😍

#109 Password strength checker
  Password-Strength-Checker/README.md
  Password-Strength-Checker/index.html
  Password-Strength-Checker/index.js
  Password-Strength-Checker/style.css
Labels: To Be Merged 😍

#111 calculator height increased to prevent buttons from flowing out
  Calculator/README.md
  Calculator/style.css
Labels: To be Fixed 😐

#138 Converters added
  Converters/README.md
  Converters/length_conv.html
  Converters/mass_conv.html
  Converters/temp_conv.html
Labels: To Be Merged 😍

#142 Guess the number
  Guess The Number/README.md
  Guess The Number/images/Screenshot (382).png
  Guess The Number/images/Screenshot (384).png
  Guess The Number/images/Screenshot (386).png
  Guess The Number/images/Screenshot (387).png
  Guess The Number/index.html
  Guess The Number/script.js
  Guess The Number/style.css
Labels: To be Fixed 😐

#154 Add Notes Taking App
  Projects Starting with N/Notes Taking App/index.html
  Projects Starting with N/Notes Taking App/script.js
  Projects Starting with N/Notes Taking App/style.css
  Projects starting with N/Notes Taking App/Readme.md
Labels: To Be Merged 😍
